---
title: craigmcn
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: therealcraigmcn@gmail.com
description: Things I think about or just find and want to share.
baseurl: ''
url: https://craigmcn.ca
twitter_username: craigmcn
github_username: craigmcn
linkedin_username: craigmcnaughton
markdown: kramdown
permalink: "/:title.html"
sass:
  style: compressed
plugins:
- jekyll-sitemap
- jekyll-redirect-from
exclude:
- vendor
