# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: craigmcn
email: therealcraigmcn@gmail.com
description: Things I think about or just find and want to share.
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://craigmcn.ca' # the base hostname & protocol for your site
twitter_username: craigmcn
github_username: craigmcn
linkedin_username: craigmcnaughton

# Build settings
markdown: kramdown

# Outputting
permalink: /:title.html
sass:
  style: compressed

# Enable sitemap and redirection
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

# Exclude?
exclude: [vendor]
