backend:
  name: github
  repo: craigmcn/craigmcn.github.io
  branch: main
  base_url: https://quiet-sunset-3f55.craig-040.workers.dev

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: posts
    label: Posts
    folder: _posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: datetime, date_format: YYYY-MM-DD, time_format: HH:mm:ssZ, format: YYYY-MM-DDTHH:mm:ssZ }
      - { label: Excerpt, name: excerpt, widget: text }
      - { label: Layout, name: layout, widget: hidden, default: post }
      - { label: Categories, name: categories, widget: list }
      - { label: Tags, name: tags, widget: list }
      - { label: Body, name: body, widget: markdown }
